version: '3.2'
services:
  openvpn:
    build: .
    container_name: openvpn
    cap_add:
     - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - type: bind
        source: ./config
        target: /etc/openvpn/config
      - type: bind
        source: ./keys
        target: /etc/openvpn/keys
